In [1]:
import numpy as np  
import matplotlib.pyplot as plt  
from mpl_toolkits.axes_grid1 import make_axes_locatable

In [2]:
%matplotlib qt5
%config InlineBackend.figure_format = 'svg'

plt.rcParams['figure.figsize'] = [12, 5]
plt.rcParams['font.size'] = 13
plt.ion()

In [4]:
def f(z):
   
    squared = z**2
    
    
    result = squared - 1
    
    return result

In [ ]:
z = [4, 1-0.2j, 1.6]
f(z)

In [6]:
f(0)

-1

In [9]:
z = [4, 1-0.2j, 1.6]

results = f(z)

print(results)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [10]:
x = np.linspace(-10, 10, 20)
y = np.linspace(-10, 10, 20)


In [12]:
x_grid, y_grid = np.meshgrid(x, y)
mesh = x_grid + y_grid * 1j

In [15]:
def f(z):
    return z**2 - 1


output = np.abs(f(mesh))

print("절대값 집합 (output):")
print(output)

절대값 집합 (output):
[[200.00249998 180.16891204 162.56186183 147.17961999 134.01873672
  123.07358959 114.33622352 107.7967979  103.44488499 101.27153785
  101.27153785 103.44488499 107.7967979  114.33622352 123.07358959
  134.01873672 147.17961999 162.56186183 180.16891204 200.00249998]
 [179.94737695 160.11392613 142.51023925 127.13547771 113.98681334
  103.05855538  94.34149584  87.82304255  83.48877541  81.32559793
   81.32559793  83.48877541  87.82304255  94.34149584 103.05855538
  113.98681334 127.13547771 142.51023925 160.11392613 179.94737695]
 [162.09770634 142.26121806 124.65775066 109.28788896  96.15018387
   85.2396981   76.54644979  70.05464703  65.74414657  63.5951671
   63.5951671   65.74414657  70.05464703  76.54644979  85.2396981
   96.15018387 109.28788896 124.65775066 142.26121806 162.09770634]
 [146.45510629 126.6114754  109.00363669  93.63414895  80.50396816
   69.6103707   60.94398894  54.48600106  50.20826791  48.07989129
   48.07989129  50.20826791  54.48600106  60

In [23]:
def divergence_rate(mesh, num_iter=10, radius=2):
    z = mesh.copy()
   
    diverge_len = np.zeros(mesh.shape)

    for i in range(num_iter):
      
        conv_mask = np.abs(z) < radius

        diverge_len[conv_mask] += 1

      
        z[conv_mask] = z[conv_mask] ** 2 - 1

    return diverge_len

x = np.linspace(-10, 10, 20)
y = np.linspace(-10, 10, 20)
x_grid, y_grid = np.meshgrid(x, y)
mesh = x_grid + y_grid * 1j

divergence_counts = divergence_rate(mesh)

print("발산 전 반복 횟수:")
print(divergence_counts)

발산 전 반복 횟수:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 3. 3. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 3. 3. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.